In [21]:
import pandas as pd

In [22]:
X = pd.read_csv('../Dataset/X_train.csv',index_col=0)
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 84916 entries, 0 to 84915
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   designation  84916 non-null  object
 1   description  55116 non-null  object
 2   productid    84916 non-null  int64
 3   imageid      84916 non-null  int64
dtypes: int64(2), object(2)
memory usage: 3.2+ MB

In [31]:
X.head(30)

,designation,description,productid,imageid
0,Olivia: Personalisiertes Notizbuch / 150 Seite...,NaN,3804725264,1263597046
1,Journal Des Arts (Le) N° 133 Du 28/09/2001 - L...,NaN,436067568,1008141237
2,Grand Stylet Ergonomique Bleu Gamepad Nintendo...,PILOT STYLE Touch Pen de marque Speedlink est ...,201115110,938777978
3,Peluche Donald - Europe - Disneyland 2000 (Mar...,NaN,50418756,457047496
4,La Guerre Des Tuques,Luc a des id&eacute;es de grandeur. Il veut or...,278535884,1077757786
5,Afrique Contemporaine N° 212 Hiver 2004 - Doss...,NaN,5862738,393356830
6,Christof E: Bildungsprozessen Auf Der Spur,NaN,91920807,907794536
7,Conquérant Sept Cahier Couverture Polypro 240 ...,CONQUERANT CLASSIQUE Cahier 240 x 320 mm seyès...,344240059,999581347
8,Puzzle Scooby-Doo Avec Poster 2x35 Pieces,NaN,4239126071,1325918866
9,Tente Pliante V3s5-Pro Pvc Blanc - 3 X 4m50 - ...,Tente pliante V3S5 Pro PVC 500 gr/m² - 3 x 4m5...,3793572222,1245644185
10,Eames Inspired Sxw Chair - Pink - Black,The timeless DSW seat can now be paired with m...,1915836983,1111840281
11,Fauteuil Chesterfield Brenton 100% Cuir De Buf...,Canapé et fauteuil chesterfield en cuir antiqu...,4127967621,1295816984
12,Peaceable Kingdom Wheres Bear? The Hide And Fi...,pCan my 2-year-old play a game? Yes Each game ...,3287127001,1204199842
13,Paire De Voilages Imprimés Fantaisie,Paire de voilages droits fantaisie qui mettra ...,1882164320,1109088140
14,Matelas Mémoire De Forme 180x200 X 20 Cm Très ...,MATELAS:<br />Â· Accueil : Ferme .<br />Â· Sou...,4108914287,1292441752
15,Zenith Pince Agrafeuse 591 N°10 Coloris Noir,Pince agrafeuse 591 N°10. Capot en ABS. Dispos...,3718150116,1237257586
16,Walter Scott Oeuvres Complètes Tomes 3456 10 E...,NaN,3735707499,1239242410
17,Mod Podge Dishwasher Safe Gloss 8oz,NaN,2666371748,1156191369
18,Power Rangers Rouge Force Mystic Figurine Tran...,NaN,91015572,857195931
19,Monde Illustre (Le) N° 3083 Du 20/01/1917 - L'...,NaN,570628142,1027257229
20,Kit de désinfection pour piscines enfants 20990,NaN,3936362802,1268740880
21,Glitter Beach Barbie By Barbie,Original Barbie Doll. Contains glitter lotion..,3228900895,1199384348
22,Le Seigneur Des Anneaux Figurine En Plomb À Pe...,NaN,1893048509,1110089245
23,Véhicule Star Wars A-Ast5,véhicule vintage de la saga star wars le A-AST5,279822475,978593209
24,Mini Wifi 720p Caméra Drone Rc Quadcopter 24 G...,Mini Wifi 720P Caméra Drone RC Quadcopter 24 G...,3748203527,1240721678
25,Dsi + Chargeur + Sacoche + 12 Jeux,NaN,211334790,948608572
26,Modèle De Voiture 4pcs Alliage Métallique 1.9i...,4pcs alliage métallique 1.9in jante de roue po...,4137059841,1297749086
27,Faber-Castell Lot De 3 Crayons De Couleur Poly...,FABER-CASTELL Crayon de couleur POLYCHROMOS ve...,2536863974,1148154575
28,Univers (L') N° 249 Du 12/09/1854 - France - P...,NaN,570663184,1027317460
29,Dragon Ball Super - Bt3-070 - C-13 Les Prémiss...,NaN,3226779852,1202890774

Les textes sont en au moins 3 langues (allemand, français, anglais), ce qui peut compliquer le NLP. Rakuten étant une entreprise mondiale, on peut s'attendre à ce que bien plus que 3 langues soient représentées dans le jeu de données.

In [28]:
y = pd.read_csv('../Dataset/Y_train.csv',index_col=0)
y.info()

<class 'pandas.core.frame.DataFrame'>
Index: 84916 entries, 0 to 84915
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   prdtypecode  84916 non-null  int64
dtypes: int64(1)
memory usage: 1.3 MB

In [29]:
y.head(15)

    prdtypecode
0            10
1          2280
2            50
3          1280
4          2705
5          2280
6            10
7          2522
8          1280
9          2582
10         1560
11         1560
12         1281
13         1920
14         1560

In [32]:
y.describe()

        prdtypecode
count  84916.000000
mean    1773.219900
std      788.179885
min       10.000000
25%     1281.000000
50%     1920.000000
75%     2522.000000
max     2905.000000

In [24]:
#TODO? histogram
# Designation lengths (character counts)
X.designation.apply(len).describe()

count    84916.000000
mean        70.163303
std         36.793383
min         11.000000
25%         43.000000
50%         64.000000
75%         90.000000
max        250.000000
Name: designation, dtype: float64

In [25]:
#TODO? histogram
# description lengths (character counts) (except for missing descriptions)
X.description.dropna().apply(len).describe()

count    55116.000000
mean       808.171692
std        805.462153
min          1.000000
25%        259.000000
50%        626.000000
75%       1034.000000
max      12451.000000
Name: description, dtype: float64

In [ ]:
#TODO wordcloud (designation / description / both)